# Generated by Django 4.0.6 on 2022-07-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Post',
        ),
    ]
