# Generated by Django 4.0.5 on 2022-07-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_rename_company_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Advertisment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('Banking', 'Banking'), ('Finance', 'Finance'), ('Tech', 'Tech'), ('Entertainment', 'Entertainment')], max_length=13),
        ),
    ]
