# Generated by Django 4.0.6 on 2022-07-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsquest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercd',
            name='user',
        ),
    ]
