# Generated by Django 4.0.6 on 2022-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_post_advertisment_remove_post_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Advertisment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('Banking', 'Banking'), ('Finance', 'Finance'), ('Tech', 'Tech'), ('Entertainment', 'Entertainment')], default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
