# Generated by Django 4.0.5 on 2022-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_post_advertisment_post_privacy_post_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='gdrp_wording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='policy_effective_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='website_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='website_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('Banking', 'Banking'), ('Finance', 'Finance'), ('Tech', 'Tech'), ('Entertainment', 'Entertainment')], max_length=13),
        ),
    ]
