# Generated by Django 4.0.5 on 2022-08-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='policy_effective_date',
            new_name='Policy_Effective_Date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='website_name',
            new_name='Your_Website_Name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='website_url',
        ),
        migrations.AddField(
            model_name='post',
            name='Your_Website_Url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
