# Generated by Django 4.0.6 on 2022-07-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
                ('data1', models.TextField()),
                ('data2', models.TextField()),
                ('data3', models.TextField()),
                ('data4', models.IntegerField()),
                ('cloc', models.TextField()),
            ],
        ),
    ]
