# Generated by Django 4.0.5 on 2022-08-08 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='website_name',
            new_name='company_address',
        ),
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Finance', 'Finance'), ('Tech', 'Tech'), ('Entertainment', 'Entertainment'), ('E-commerce', 'E-Commerce')], default='Generic', max_length=13),
        ),
        migrations.AlterField(
            model_name='post',
            name='policy_effective_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='website_url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
