# Generated by Django 4.0.6 on 2022-08-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_company_name_post_website_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='term',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='company_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='policy_effective_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='website_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
